---
# tasks file for roles/web
---
- name: Configure Instance
  hosts: web
  gather_facts: true
  become: true
  tasks:
   - name: Install nginx
      apt:
        name: nginx
        update_cache: true


   - name: Install git
      apt:
        name: git
        state: present
        update_cache: true


   - name: Git clone
      git:
        repo: "https://github.com/nicolas-hermosilla/TP_final_jenkins_pipeline2 /var/www/html/"

