---
# tasks file for roles/web
- name : Install docker
  apt:
    name: docker-compose
    state: latest
    update_cache: true


- name : Add user to docker group
  user:
     name : ubuntu
     groups: docker
     append: yes
  become : yes

- name : Clone a public repository
  git:
    repo: 'https://github.com/j0h3/cours_ynov'
    dest: /home/ubuntu/cours_ynov


